### ISSUE TITLE
Max length of context

### ISSUE THREAD

**Issue by bpucla** [facebookresearch/MetaICL#11]
Thank you for your great work! It's very inspiring. 

I would like your help to clarify on one point. The input to the model is `x_1, y_1, ..., x_k, y_k, x_k+1` where k = 16 in your experiment settings. And the maximum length of the model is `1024`. My question is how 16 examples in some datasets with long text can be fit to `1024`? 

Consider Xsum (used in the HR -> LR setting), where the average document length is 431 and the average summary length 23. Thus roughly one example has an average length  of `450`. If the long context is truncated, then the maximum length `1024` only affords less than `3` examples on average, which is far below `16`. 

With the maximum length limit and the experiment settings, I assume that's the only available solution. I just would like to know what you did in your experiments and if you have any suggestions on how resolve this issue. 

Thank you very much in advance!

**Comment by shmsw25** [comment]
Hi, thanks for the question! We truncate each example to be up to 256 tokens, and then concatenate them to be up to 1024. It is true that how it works is not very good for tasks with long inputs, like Xsum.
