### ISSUE TITLE
Checksum error in datasets==1.4.0

### ISSUE THREAD

**Issue by AlexWan0** [facebookresearch/MetaICL#13]
Was getting checksum errors when downloading data for a few datasets in _build_gym.py. Seems to be this error: https://github.com/huggingface/datasets/pull/3787

I've been using the latest version of datasets==2.4.0, and it seems to be working alright for the few runs that I did.

**Comment by shmsw25** [comment]
Thank you for the report! I am actually unable to reproduce the error (even after clearing the cache) for some reason. I think using `datasets==2.4.0` is fine, unless you want to exactly reproduce the numbers in the paper (because a few datasets may have minor changes).
