### ISSUE TITLE
Why using [SEP] token while using gpt2 tokenizer?

### ISSUE THREAD

**Issue by wookjeHan** [facebookresearch/MetaICL#14]
Hi, I have a question about data preprocessing.

I noticed that the code used `[SEP]` when proprocessing dataset such as superglue rte or wic.

However, I am wondering why metaICL selects `[SEP]` token while it uses `gpt2` tokenizer.

The reason why I think this is strange is because according to my understanding, `gpt2` tokenizer doesn't handle `[SEP]` token.

It just tokenizes to `[, SE, P, ]`.

Would you please explain the reason of using `[SEP]` token?

Thanks in advance.
Best regards,
Wookje Han

**Comment by shmsw25** [comment]
Hi @wookjeHan, thanks for the question. We followed the exact preprocessing from [CrossFit](https://github.com/INK-USC/CrossFit) which used `[SEP]`. You are right that GPT2 tokenizer won't consider it as one token, but we treat it as a special indicator that indicates they are two different sentences. In the early stage of the project, we also explored removing it and the results were not very different (for both baselines and ours), so chose to follow CrossFit as exactly as it is for consistency. If you prefer, I think you can remove the [SEP] token entirely (or use your own, manually-written template to indicate these are two separate sentences).

**Comment by wookjeHan** [comment]
Oh I understand.
Thanks for your kind reply. It helped me a lot.
Best regards,
Wookje Han
