### ISSUE TITLE
Reproducibility of PMI methods?

### ISSUE THREAD

**Issue by JunShern** [facebookresearch/MetaICL#5]
Hi, I tried running `reproduce.sh` exactly as described https://github.com/JunShern/MetaICL#simply-reproducing-all-results-in-the-paper, and so far the results I get do exactly match the reported results in the README, **except for the `pmi-zero` and `pmi-ic` settings.**

From the README:

  | hr_to_lr | class_to_class | non_class_to_class | qa_to_qa | non_qa_to_qa | non_nli_to_nli | non_paraphrase_to_paraphrase
-- | -- | -- | -- | -- | -- | -- | --
zero | 34.9 | 34.2 | 34.2 | 40.4 | 40.4 | 25.5 | 34.2
pmi-zero | 34.8 | **33.2** | **33.2** | 40.4 | 40.4 | 27.9 | 39.2
channel-zero | 36.8 | 37.2 | 37.2 | 39.2 | 39.2 | 33.9 | 39.5
ic | 38.2 | 37.4 | 37.4 | 40.2 | 40.2 | 34 | 33.7
pmi-ic | 38.9 | 38.3 | 38.3 | 40.5 | 40.5 | 33 | 38.6

The results I get:

  | hr_to_lr | class_to_class | non_class_to_class | qa_to_qa | non_qa_to_qa | non_nli_to_nli | non_paraphrase_to_paraphrase
-- | -- | -- | -- | -- | -- | -- | --
zero | 34.9 | 34.2 | 34.2 | 40.4 | 40.4 | 25.5 | 34.2
pmi-zero | 31.3 | **24.1** | **24.1** | 36.4 | 36.4 | 26 | 33.1
channel-zero | 36.8 | 37.2 | 37.2 | 39.2 | 39.2 | 33.9 | 39.5
ic | 38.2 | 37.4 | 37.4 | 40.2 | 40.2 | 34 | 33.7
pmi-ic | 37.6 | 35.8 | -- | -- | -- | 31.7 | 32.9

(Ignore the -- above, I have not gotten results for those yet.)

If you compare the tables, you will see that all the rows are identical except for `pmi-zero` and `pmi-ic`. In particular, if you compare `class_to_class` and `non_class_to_class` settings for `pmi-zero`, the difference is as much as 9%.

Is this expected / Do you have any guess why this happens?

**Comment by shmsw25** [comment]
Thanks for reporting and sorry about the inconvenient. Actually, [this line](https://github.com/JunShern/MetaICL/blob/main/utils/data.py#L33) should change from `dp["input"] = ""` to `dp["input"] = "N/A"`, following Zhao et al 2021. I tested `hr_to_lr` zero-shot, and confirmed that the result is reproducible. I will complete all other experiments and then push the commit with the update.

**Comment by shmsw25** [comment]
After changing `""` to `"N/A"`, looks like all results are reproducible, and I pushed a new commit. Let me know if you still have an issue reproducing the result!

**Comment by JunShern** [comment]
Thanks very much! I've run the evaluations again and was able to confirm that the results are now as expected.
